version: '3'

services:
     mailhog:
          image: mailhog/mailhog
          ports:
               - '1025:1025'
               - '8025:8025'
     app:
          build: .
          command: npm run start:dev
          working_dir: /usr/src/app
          environment:
               - MAIL_HOST=mailhog
               - MEDIA_FILES_DEST=/uploads
          ports:
               - '3000:3000'
          volumes:
               - ./uploads:/uploads
               - .:/usr/src/app
          depends_on:
               - mailhog
